import { StyleSheet } from 'react-native';

export const colors = {
  background: '#FDF8F0',
  green: '#1BBF3E',
  orange: '#F58C00',
  dark: '#1A1A1A',
  gray: '#777',
  card: '#FFFFFF',
};

export const styles = StyleSheet.create({
  fullScreen: { flex: 1 },
  introOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.45)' },
  splashScreenContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 20 },
  splashTitle: { fontSize: 36, fontWeight: '900', color: '#fff', textShadowColor: 'rgba(0,0,0,0.42)', textShadowOffset: { width: 0, height: 3 }, textShadowRadius: 8 },
  splashSubtitle: { marginTop: 12, color: '#fff', fontSize: 16, textAlign: 'center', maxWidth: 280 },
  introContent: { flex: 1, justifyContent: 'flex-end', padding: 28 },
  introBigTitle: { color: '#fff', fontSize: 42, fontWeight: '900', marginBottom: 14 },
  introText: { color: '#fff', fontSize: 16, maxWidth: 320, marginBottom: 24 },
  getStartedBtn: { backgroundColor: colors.orange, paddingVertical: 16, borderRadius: 14, alignItems: 'center', marginBottom: 56 },
  getStartedText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  safeArea: { flex: 1, backgroundColor: colors.background },
  dashboardContainer: { flexGrow: 1, padding: 20, paddingTop: 28, paddingBottom: 24, backgroundColor: colors.background },
  detailContainer: { padding: 20, paddingTop: 40, paddingBottom: 36, backgroundColor: colors.background },
  dashboardHeader: { marginTop: 56, paddingTop: 24, paddingBottom: 14, marginBottom: 18, backgroundColor: '#151515', borderRadius: 18, borderWidth: 1, borderColor: '#333', paddingHorizontal: 12, shadowColor: '#000', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.2, shadowRadius: 8, elevation: 6 },
  dashboardTitle: { fontSize: 30, fontWeight: '900', color: '#fff', letterSpacing: 0.25 },
  dashboardTitleCentered: {
  fontSize: 30,
  fontWeight: '900',
  color: '#fff',
  textAlign: 'center',
},
  dashboardSubtitle: { color: '#bbb', marginTop: 6, fontSize: 16, lineHeight: 22 },
  searchClearBtn: { width: 34, height: 34, justifyContent: 'center', alignItems: 'center', marginHorizontal: 4, borderRadius: 18, backgroundColor: '#f1f1f1' },
  searchClearText: { color: '#444', fontSize: 20, fontWeight: '800' },
  searchBtn: { backgroundColor: colors.orange, paddingHorizontal: 18, borderRadius: 20, paddingVertical: 12, minWidth: 70, justifyContent: 'center', alignItems: 'center' },
  searchBtnText: { color: '#fff', fontWeight: '700', fontSize: 15 },
  sectionTitle: { fontSize: 20, fontWeight: '700', marginBottom: 2 },
  sectionSubtitle: { color: '#666', fontSize: 14, marginTop: 2, marginBottom: 10 },
centeredLoader: {
  flex: 1,
  width: '100%',
  justifyContent: 'center',
  alignItems: 'center',
},
centeredLoaderText: {
  marginTop: 10,
  color: '#ffffff',
  textAlign: 'center',
  width: '100%', 
},
searchRow: {
  flexDirection: 'row',
  alignItems: 'center',
  marginBottom: 20,
},

searchSection: {
  flex: 1,
  flexDirection: 'row',
  alignItems: 'center',
  borderRadius: 24,
  backgroundColor: '#fff',
  paddingHorizontal: 14,
  height: 52,
  shadowColor: '#000',
  shadowOpacity: 0.08,
  shadowRadius: 6,
  elevation: 3,
},

searchInput: {
  flex: 1,
  fontSize: 15,
  color: '#222',
  borderWidth: 0,
},  
refreshingBanner: {
  width: '100%',
  marginHorizontal: -20, // fix: cancels parent padding
  paddingHorizontal: 20, // keeps inner spacing clean
  backgroundColor: '#FFF4E6',
  paddingVertical: 6,
  borderRadius: 12,
  marginBottom: 10,
  borderWidth: 1,
  borderColor: '#F2C49A',
  alignItems: 'center',
  justifyContent: 'center',
},  refreshingBannerText: { color: '#ffffff', fontSize: 13, fontWeight: '600' },
  noFavoritesContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 16 },
  noFavoritesMessage: { alignItems: 'center' },
  noFoodContainerCentered: { justifyContent: 'center', alignItems: 'center' },
  sectionHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 12, marginBottom: 8 },
  cardChevron: { position: 'absolute', bottom: 8, right: 10, color: '#fff', fontSize: 19, opacity: 0.9 },
  filterSummaryContainer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#FFF4E6', borderRadius: 12, borderWidth: 1, borderColor: '#F2C49A', paddingHorizontal: 12, paddingVertical: 8, marginBottom: 10 },
  filterSummaryText: { color: '#664f3a', fontSize: 14, fontWeight: '600' },
  clearFilterBtn: { backgroundColor: '#FFE5CC', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8, borderWidth: 1, borderColor: '#fbbb78' },
  clearFilterText: { color: '#a05a0a', fontWeight: '700', fontSize: 13 },
favoritesOverview: {
  marginBottom: 18,
  padding: 18,
  borderRadius: 18,
  backgroundColor: '#FDEBDD', // softer warm tone
  shadowColor: '#000',
  shadowOpacity: 0.08,
  shadowRadius: 8,
  elevation: 3,
},
 favoritesTitle: {
  fontSize: 18,
  fontWeight: '800',
  color: '#1A1A1A',
  marginBottom: 4,
},

 favoriteCountText: { fontSize: 16, marginTop: 4, color: '#5d4a35', fontWeight: '600' },
  dashboardControls: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  controlBtn: { flex: 1, marginRight: 8, paddingVertical: 8, borderRadius: 12, borderWidth: 1, borderColor: '#ddd', backgroundColor: '#fff', alignItems: 'center' },  controlBtnActive: { backgroundColor: '#fde5d2', borderColor: colors.orange },
  controlBtnText: { color: '#444', fontWeight: '600' },
  controlBtnTextActive: { color: colors.orange },
  statsText: { marginBottom: 12, color: '#666', fontSize: 13, fontWeight: '600' },
  categoryScroll: { marginTop: 2, marginBottom: 4 },
  categoryScrollContent: { paddingLeft: 0, paddingRight: 8, alignItems: 'center' },
  categoryHintText: { fontSize: 12, color: '#55606a', marginBottom: 4, paddingHorizontal: 4 },
  categoryChip: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 24, backgroundColor: '#fff', borderWidth: 1, borderColor: colors.orange, marginRight: 4, marginBottom: 4, minWidth: 90, alignItems: 'center' },  categoryChipActive: { backgroundColor: colors.orange, borderColor: '#e68a00' },
  categoryChipText: { color: '#333', fontWeight: '600', fontSize: 12 },
  categoryChipTextActive: { color: '#fff' },
  justForYouRow: { flexDirection: 'row', flexWrap: 'nowrap', alignItems: 'center', marginBottom: 12 },
  justForYouScroll: { paddingBottom: 10 },
  justForYouScrollContent: { paddingRight: 10 },
  smallCard: { width: 260, height: 235, borderRadius: 14, overflow: 'hidden', backgroundColor: '#111', elevation: 14, borderWidth: 1, borderColor: '#000', shadowColor: '#000', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.35, shadowRadius: 14, marginBottom: 14, marginRight: 14 },
  smallCardImage: { width: '100%', height: 140, resizeMode: 'cover' },
  smallCardTextArea: { paddingHorizontal: 12, paddingTop: 10, paddingBottom: 10, backgroundColor: '#111', minHeight: 90, justifyContent: 'space-between' },
  smallCardText: { fontSize: 12.5, fontWeight: '800', color: '#fff', lineHeight: 16, marginBottom: 4, maxHeight: 36, flexWrap: 'wrap' },
  ratingRow: { flexDirection: 'row', marginTop: 4, height: 24, alignItems: 'center' },
  ratingRowCentered: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginTop: 4, marginBottom: 8, height: 24 },
  star: { fontSize: 20, color: '#FFD700' },
  starButton: { minWidth: 30, minHeight: 30, marginHorizontal: 1, borderRadius: 18, justifyContent: 'center', alignItems: 'center' },
  starActive: { color: '#FFD700' },
  starInactive: { color: '#B5B5B5' },
  noFoodContainer: { flexGrow: 1, justifyContent: 'flex-start' },
  noFoodPlaceholder: { padding: 14, backgroundColor: '#fff9e8', borderRadius: 16, borderWidth: 1, borderColor: '#e5d7ba', alignItems: 'center', marginTop: 4, width: '100%' },  noFoodText: { color: '#333', fontSize: 16, fontWeight: '700', textAlign: 'center', marginBottom: 6 },
  noFoodSubText: { color: '#666', fontSize: 14, textAlign: 'center' },
  emptyLabel: { color: '#999', fontSize: 14 },
  columnWrapper: { justifyContent: 'space-between', marginBottom: 14 },
  trendCard: { width: '48%', borderRadius: 16, overflow: 'hidden', marginBottom: 16, minHeight: 210, backgroundColor: '#000', elevation: 12, borderWidth: 1, borderColor: '#000', shadowColor: '#000', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.3, shadowRadius: 12 },
  trendImage: { width: '100%', height: 140, resizeMode: 'cover' },
  trendOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.42)' },
  trendLabelContainer: { position: 'absolute', bottom: 0, left: 0, right: 0, height: 76, paddingTop: 8, paddingBottom: 8, paddingHorizontal: 10, backgroundColor: 'rgba(0,0,0,0.70)', borderBottomLeftRadius: 16, borderBottomRightRadius: 16, justifyContent: 'flex-start' },
  trendTitle: { color: '#fff', fontWeight: '700', fontSize: 12.5, flexWrap: 'wrap', lineHeight: 16, maxHeight: 36, marginBottom: 8 },
  trendRatingRow: { flexDirection: 'row', justifyContent: 'flex-start', alignItems: 'center', marginTop: 0 },
  trendStarButton: { marginHorizontal: 1, width: 24, height: 24, justifyContent: 'center', alignItems: 'center' },
  trendStar: { fontSize: 18, lineHeight: 20 },
favoriteIconBtn: {
  marginLeft: 8,
  width: 44,
  height: 44,
  borderRadius: 22,
  backgroundColor: '#fff',

  alignItems: 'center',
  justifyContent: 'center',

  shadowColor: '#000',
  shadowOpacity: 0.1,
  shadowRadius: 4,
  elevation: 3,
},
  favoriteIconBtnActive: { borderColor: colors.orange, backgroundColor: '#ffe9dc' },
  favoriteIconText: { color: '#888', fontSize: 26, fontWeight: '800' },
  favoriteIconTextActive: { color: colors.orange },
  favoriteBadge: { position: 'absolute', top: 12, right: 12, zIndex: 2, width: 34, height: 34, borderRadius: 17, backgroundColor: 'rgba(255,255,255,0.9)', alignItems: 'center', justifyContent: 'center' },
  favoriteText: { color: '#FF6B81', fontSize: 14 },
  favoriteTextActive: { color: '#FF1F66' },
  statusContainer: { justifyContent: 'center', alignItems: 'center', marginVertical: 20 },
  loadingText: { marginTop: 12, color: '#666' },
  errorMsg: { color: '#D32F2F', textAlign: 'center', marginBottom: 8 },
  retryBtn: { backgroundColor: colors.orange, borderRadius: 10, paddingHorizontal: 16, paddingVertical: 10 },
  btnText: { color: '#fff', fontWeight: '700' },
  noFoodBottomText: { textAlign: 'center', color: '#888', fontSize: 15, fontStyle: 'italic', marginTop: 32, paddingBottom: 50, paddingHorizontal: 20, lineHeight: 22 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.48)', justifyContent: 'flex-end', alignItems: 'center', padding: 8 },
  modalContent: { backgroundColor: '#fff', width: '95%', borderRadius: 24, maxHeight: '85%', padding: 16, paddingBottom: 24, elevation: 12 },
  modalHeaderRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 6 },
  modalTitle: { flex: 1, fontSize: 22, fontWeight: 'bold', color: colors.dark },
  bookmarkBtn: { padding: 6 },
  bookmarkText: { fontSize: 20, color: colors.orange },
  mealLabel: { color: '#777', marginBottom: 10 },
  sectionSubheading: { fontWeight: '700', marginTop: 8, marginBottom: 8 },
  cardBlock: { backgroundColor: '#fff', borderRadius: 16, borderWidth: 1, borderColor: '#ddd', padding: 12, marginBottom: 14, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.08, shadowRadius: 10, elevation: 3 },
  progressBarContainer: { width: '100%', height: 10, backgroundColor: '#F3F7F1', borderRadius: 8, overflow: 'hidden', marginTop: 8, marginBottom: 8 },
  progressBarFill: { height: '100%', backgroundColor: colors.orange, borderRadius: 8 },
  progressText: { fontSize: 13, color: '#4b4b4b', marginBottom: 6, fontWeight: '600' },
  ingredientRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6, backgroundColor: '#F8F6F1', borderRadius: 8, padding: 10, alignItems: 'center' },
  ingredientName: { flex: 1, fontWeight: '500', color: '#444', marginRight: 12, flexWrap: 'wrap' },
  ingredientAmount: { minWidth: 70, color: '#666', textAlign: 'right', flexShrink: 0 },
  ingredientAmountEmpty: { color: '#999', fontStyle: 'italic' },
  stepControlsRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 10 },
  nextStepBtn: { flex: 1, backgroundColor: colors.green, borderRadius: 10, paddingVertical: 10, alignItems: 'center', marginRight: 8 },
  nextStepBtnDisabled: { backgroundColor: '#C4C4C4', opacity: 0.6 },
  nextStepBtnText: { color: '#fff', fontWeight: '700' },
  resetStepBtn: { paddingVertical: 10, paddingHorizontal: 14, borderRadius: 10, borderWidth: 1, borderColor: colors.orange, backgroundColor: '#fff', justifyContent: 'center', alignItems: 'center' },
  resetStepBtnText: { color: colors.orange, fontWeight: '700' },
  stepRowActive: { backgroundColor: '#E5F7E9', borderRadius: 10, padding: 8 },
  stepNumberActive: { color: colors.green },
  stepTextActive: { color: '#1a5827' },
  modalText: { color: '#546068', lineHeight: 20 },
  modalActionsRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 14 },
  modalHandle: { alignSelf: 'center', width: 40, height: 5, borderRadius: 3, backgroundColor: '#D1D5DB', marginBottom: 12 },
  shareBtn: { flex: 1, backgroundColor: colors.orange, borderRadius: 12, paddingVertical: 10, alignItems: 'center', marginRight: 8 },
  shareBtnText: { color: '#fff', fontWeight: '700' },
  closeBtn: { flex: 1, borderWidth: 1, borderColor: '#ccc', borderRadius: 12, paddingVertical: 10, alignItems: 'center' },
  closeBtnText: { color: '#333', fontWeight: '700' },
  detailHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 14, marginTop: 10, paddingTop: 40, paddingHorizontal: 4 },
backBtn: {
  marginRight: 10,
  padding: 8,
  borderRadius: 12,
  backgroundColor: '#222',
},



backArrow: {
  fontSize: 26, // 🔥 BIG arrow
  color: '#fff',
  marginRight: 4,
  width: 50, // keeps touch area generous
  height: 30, // keeps touch area generous
  lineHeight: 30, // vertically center the arrow

},

  backButton: {
  flexDirection: 'row',
  alignItems: 'center',
  backgroundColor: '#222',
  paddingHorizontal: 14,
  paddingVertical: 8,
  borderRadius: 14,
  marginRight: 12,
},

backButtonText: {
  color: '#fff',
  fontSize: 14,
  fontWeight: '600',

},
backButtonFull: {
  width: '20%',
  backgroundColor: '#1f1f1f',
  paddingVertical: 12,
  paddingHorizontal: 14,
  borderRadius: 16,
  marginBottom: 12,
},
  detailTitle: { flex: 1, fontSize: 26, fontWeight: '900', color: colors.dark },
  detailImage: { width: '100%', height: 240, borderRadius: 16, marginBottom: 12 },
  subTitle: { color: '#405b4b', marginBottom: 12, fontWeight: '600' },
  instructionsContainer: { backgroundColor: '#f3f7f1', borderRadius: 12, padding: 12, marginBottom: 14 },
  stepRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 10 },
  stepNumber: { width: 24, textAlign: 'center', marginRight: 10, color: colors.green, fontWeight: '700' },
  stepText: { flex: 1, color: '#2a3b31', lineHeight: 22 },
  detailActionsRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 18 },
});